spring:

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/books_db
    username: postgres
    password: postgres
    hikari:
      schema: books_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS books_schema
      connection-timeout: 10000

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

app:
  redis:
    enable: true

  cache:
    cacheType: redis
    cache-names:
      - bookByNameAndAuthor
      - booksByCategories
    caches:
      bookByNameAndAuthor:
        expiry: 10s
      booksByCategories:
        expiry: 10s

logging:
  level:
    root: debug

