spring:

  profiles:
    active: dev

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/books_db
    username: postgres
    password: postgres
    hikari:
      schema: books_schema
      connection-timeout: 10000

  jpa:
    hibernate:
      ddl-auto: none

app:
  redis:
    enable: true

  cache:
    cacheType: redis
    cache-names:
      - bookByNameAndAuthor
      - booksByCategories
    caches:
      bookByNameAndAuthor:
        expiry: 10m
      booksByCategories:
        expiry: 10m
