DROP TABLE IF EXISTS books_schema.books;
DROP TABLE IF EXISTS books_schema.categories;


CREATE TABLE books_schema.categories (
                                         id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                         "name" varchar(255) NULL,
                                         CONSTRAINT categories_pkey PRIMARY KEY (id)
);

CREATE TABLE books_schema.books (
                                    category_id int8 NOT NULL,
                                    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                    "name" varchar(255) NULL,
                                    author varchar(255) NULL,
                                    CONSTRAINT books_pkey PRIMARY KEY (id)
);

ALTER TABLE books_schema.books ADD CONSTRAINT fkleqa3hhc0uhfvurq6mil47xk0 FOREIGN KEY (category_id) REFERENCES books_schema.categories(id);